### ISSUE TITLE
Help running this project

### ISSUE THREAD

**Issue by id4github** [OrangeTux/CS#1]
I tried to run this code.
I am getting bad request error.
 
![Screenshot_1](https://user-images.githubusercontent.com/8154998/62519204-c001a480-b848-11e9-86b1-a423739b3235.png)
![Screenshot_2](https://user-images.githubusercontent.com/8154998/62519205-c001a480-b848-11e9-846b-3ae42225d4e1.png)

**Comment by deepakEnercent** [comment]
@OrangeTux Hi i need help in this exactly the same issues.new to python and difficult to understand.

**Comment by OrangeTux** [comment]
This project isn't really supported anymore.
